### PR TITLE
Open ShowMore elemetn when user clicks on a hash anchor inside

### LINKED ISSUE #1715: Broken scrolling when clicking a table of content in the forums
Clicking on a table of contents in a forum topic for a movie submission allows you to scroll through the submission text, which normally cannot be scrolled through.

Here's a video showing it in action: https://youtu.be/cKDdoK5HNHU
Here's the page used for the demonstration: https://tasvideos.org/Forum/Topics/24897

A suggestion on how to fix it would be to expand the submission text if an option in a table of contents is clicked.

### PR DESCRIPTION
**Pull request by Masterjun3**
Resolves #1715 .

### CODE REVIEW

File: TASVideos/wwwroot/js/show-more.js [hunk 1]
```diff
@@ -37,4 +37,10 @@ function registerShowMore(content) {
 
     show.querySelector('a').onclick = () => false;
     hide.querySelector('a').onclick = () => false;
+
+    content.onclick = function (e) {
+        if (e.target.tagName === "A" && e.target.getAttribute('href')?.startsWith('#') && content.style.overflowY === "hidden") {
```
Comment (adelikat) [inline TASVideos/wwwroot/js/show-more.js:42]: Can we consistently use single quotes?

Comment (Masterjun3) [reply TASVideos/wwwroot/js/show-more.js:42]: Sure! But there are other instances of double quotes in this file that I haven't touched.

**Review by adelikat — APPROVED** [review]
